logging:
  level:
    org.springframework.data.r2dbc: DEBUG
spring:
  r2dbc:
    url: r2dbc:mssql://localhost:1433/shoe_store_db?currentSchema=shoe_store_schema
    username: sa
    password: n.lvov_1705
