logging:
  level:
    org.springframework.data.r2dbc: DEBUG
spring:
  r2dbc:
    url: r2dbc:mssql://localhost:1433/shoe_store_db
    username: nikitecc
    password: n_lvov1705
  sql:
    init:
      mode: always